### ISSUE TITLE
Can't find QR code file at /tmp/xx.png

### ISSUE THREAD

**Issue by chenchangjv** [RikkaApps/FCM-for-Mojo#129]
[18/08/31 22:33:44] [info] 等待手机QQ扫描二维码...
[18/08/31 22:35:46] [info] 登录二维码已失效，重新获取二维码
[18/08/31 22:35:46] [info] 正在获取登录二维码...
[18/08/31 22:35:46] [info] 清除残留的历史二维码图片
[18/08/31 22:35:46] [info] 二维码已下载到本地[ /tmp/mojo_webqq_qrcode_ffm.png ]
[FFM] QRCode Link: http://localhost:5004/ffm/get_qr_code
[FFM] /ffm/send
[FFM] do not send because ids is empty

But 5004 refused to connect and QR code picture was not in /tmp directory

**Comment by WordlessEcho** [comment]
You should not directly visit your server to get QR code because FFM will automatically get it. In addition, `localhost` will only listen the request from the local.
Add your device in _manage devices_ , and restart FFM server. FFM will prompt a message to help you find the QR code.

**Comment by chenchangjv** [comment]
I think it won't work as you said. I tried to get QR code in FFM, but it get 401 unauthorized error. On the other hand, I requested 5004 port in localhost and was refused. I would try again as soon as possible for I have uninstalled Google Service.

**Comment by WordlessEcho** [comment]
`[FFM] do not send because ids is empty` This mean you haven’t add devices on FFM client. 
You can get code by visit [your server]:5005/ffm/get_qr_code at remote, or visit link in log on your server. 
You might set HTTP base authority but input wrong password, so you get 401 error.
If you think your device to the FCM service have some trouble, input `*#*#426#*#*` to check log.
